//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class SeventhChord
{
    public int Id { get; set; }
    public string Root { get; set; }
    public string Third { get; set; }
    public string Fifth { get; set; }
    public string Seventh { get; set; }
    public int SeventhChordQualityId { get; set; }

    public virtual SeventhChordQuality SeventhChordQuality { get; set; }
}

public partial class SeventhChordQuality
{
    public SeventhChordQuality()
    {
        this.SeventhChords = new HashSet<SeventhChord>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<SeventhChord> SeventhChords { get; set; }
}

public partial class Triad
{
    public int Id { get; set; }
    public string Root { get; set; }
    public string Third { get; set; }
    public string Fifth { get; set; }
    public int TriadQualityId { get; set; }

    public virtual TriadQuality TriadQuality { get; set; }
}

public partial class TriadQuality
{
    public TriadQuality()
    {
        this.Triads = new HashSet<Triad>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Triad> Triads { get; set; }
}

public partial class User
{
    public int Id { get; set; }
    public string Name { get; set; }
    public double SessionPercentage { get; set; }
    public double BestPercentage { get; set; }
    public System.DateTime CreateDateTime { get; set; }
    public System.DateTime UpdateDateTime { get; set; }
}
